export default {
  100: { label: "합동 안전점검", isApproval: false, usePrint: true, hidePrintTitle: true },
  101: { label: "안전보건 경영방침", isApproval: false, usePrint: true },
  102: { label: "안전보건총괄책임자 업무 수행평가", isApproval: false, usePrint: true },
  104: { label: "하도급업체 정보", isApproval: false, usePrint: true },
  107: { label: "안전·보건교육", isApproval: false, usePrint: true, hidePrintTitle: true, usePrevPost: true },
  114: { label: "시설물 점검", isApproval: true, usePrint: true },
  116: { label: "(재해발생) 산업재해 발생 시 보고 절차 안내", isApproval: false, usePrint: true },
  117: { label: "산업재해조사표", isApproval: false, usePrint: true, hidePrintTitle: true },
  118: { label: "계약정보", isApproval: true, usePrint: true },

  126: { label: "안전보건 조직 체계도", isApproval: false, usePrint: true, hidePrintTitle: true },

  127: { label: "안전보건관리책임자 업무 수행평가", isApproval: false, usePrint: true },
  128: { label: "관리감독자 업무 수행평가", isApproval: false, usePrint: true },
  129: { label: "종사자 참여 평가", isApproval: false, usePrint: true },
  130: { label: "하도급업체 수행평가", isApproval: false, usePrint: true },
  131: { label: "수시 점검표", isApproval: false, usePrint: true },

  132: { label: "교육 모니터링", isApproval: true, usePrint: true },
  134: { label: "반기별 보고", isApproval: false, usePrint: true },

  136: { label: "안전보건 점검 인력", isApproval: true, usePrint: true },
  137: { label: "안전보건 점검 계획", isApproval: false, usePrint: true, listType: "list137" },
  138: { label: "비상 연락/지원 체계도", isApproval: true, usePrint: true },
  139: { label: "유관기관 비상연락망", isApproval: false, usePrint: true, hidePrintTitle: true },
  140: { label: "안전보건관리체계 구축 현황", isApproval: false, usePrint: true },
  141: { label: "안전보건 조직도", isApproval: true, usePrint: true },
  142: { label: "내부종사자 정보", isApproval: false, usePrint: true },

  146: { label: "공사안전보건대장", isApproval: false, usePrint: true, usePrintTitle: false, usePrevPost: true },
  149: { label: "수급인 산재예방 평가", isApproval: true, usePrint: true },
  150: { label: "안전보건 확보 의무", isApproval: false, usePrint: true },
  151: { label: "위험성평가협의회", isApproval: true, usePrint: true },
  152: { label: "산업안전보건위원회", isApproval: false, usePrint: true, usePrevPost: true },
  153: { label: "노사협의체", isApproval: false, usePrint: true, usePrevPost: true },

  161: { label: "정기 위험성평가", isApproval: false, usePrint: true, usePrevPost: true, printDirection: "landscape" },
  162: { label: "수시 위험성평가", isApproval: false, usePrint: true, usePrevPost: true, printDirection: "landscape" },

  163: { label: "작업장 순회점검일지", isApproval: false, usePrint: true, hidePrintTitle: true },
  164: { label: "요양보호사", isApproval: true, usePrint: true },
  165: { label: "종사자 및 주차시설", isApproval: true, usePrint: true },
  166: { label: "냉온수기 및 보일러 설비", isApproval: true, usePrint: true },
  167: { label: "행사자 동선 및 관계자", isApproval: true, usePrint: true },
  168: { label: "시설물 관리(공통)", isApproval: true, usePrint: true },

  219: { label: "(건설현장) 건설기계·장비별 안전점검표", isApproval: false, usePrint: true, hidePrintTitle: true },
  220: { label: "(건설현장) 위험작업별 안전점검표", isApproval: false, usePrint: true, hidePrintTitle: true },

  234: { label: "시설물 진단", isApproval: true, usePrint: true },
  235: { label: "시설물 보수", isApproval: true, usePrint: true },
  236: { label: "시설물 보강", isApproval: true, usePrint: true },
  237: { label: "시설물 교체", isApproval: true, usePrint: true },

  238: { label: "(재해발생) 비상조치 및 처리 절차 안내", isApproval: false, usePrint: true },
  239: { label: "비상대피 훈련", isApproval: false, usePrint: true },
  240: { label: "비상대피 교육", isApproval: false, usePrint: true },
  241: { label: "비상대피 자체평가", isApproval: false, usePrint: true },

  244: { label: "중대재해 발생 보고", isApproval: false, usePrint: true, hidePrintTitle: true },

  246: { label: "안전작업계획서(고위험작업)", isApproval: false, usePrint: true, hidePrintTitle: true, usePrevPost: true },
  250: { label: "산업안전보건관리비", isApproval: false, usePrint: true, useHeaderDate: false },

  256: { label: "최초 위험성평가", isApproval: false, usePrint: true, usePrevPost: true, printDirection: "landscape" },
  257: { label: "작업허가서", isApproval: false, usePrint: true, hidePrintTitle: true, usePrevPost: true },
  259: { label: "안전 및 보건에 관한 협의체", isApproval: false, usePrint: true, hidePrintTitle: true, usePrevPost: true },
  261: { label: "일일 안전보고 일지", isApproval: false, usePrint: true, hidePrintTitle: true, useDelete: true, useHeaderDate: false, usePrevPost: true },
  282: { label: "관리감독자 선임", isApproval: false, usePrint: true, printLabel: "지정서 출력", hidePrintTitle: true },
  284: { label: "관리책임자 안전보건 경영방침 작성", isApproval: false, usePrint: true, hidePrintTitle: true },
  285: { label: "안전보건관리(총괄)책임자 선임", isApproval: false, usePrint: true, printLabel: "지정서 출력", hidePrintTitle: true },
  300: { label: "테이블아이템", isApproval: true, usePrint: true, useHeaderDate: false },
  307: { label: "안전사고 발생 보고서", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  308: { label: "재발방지 조치 보고서", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  309: { label: "일반재해 산재업무 처리절차", isApproval: false, usePrint: true, useHeaderDate: false, hideFileDownload: true },
  310: { label: "중대재해 산재업무 처리절차", isApproval: false, usePrint: true, useHeaderDate: false, hideFileDownload: true },
  326: { label: "장마철(태풍)", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  327: { label: "동절기", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  328: { label: "해빙기", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  329: { label: "산업안전보건관리비(하도급업체)", isApproval: false, usePrint: true, useHeaderDate: false },
  330: { label: "안전 및 보건에 관한 협의체 위임장", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  331: { label: "안전개선 제안서", isApproval: false, usePrint: true, useHeaderDate: false },
  332: { label: "위험성평가 회의록", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  333: { label: "위험성평가 회의록", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  334: { label: "위험성평가 회의록", isApproval: false, usePrint: true, useHeaderDate: false, hidePrintTitle: true },
  335: { label: "하도급업체 등록", isApproval: false, usePrint: true, hideFileDownload: true },
  336: { label: "본사(현장) ID 등록", isApproval: false, usePrint: true, hideFileDownload: true },
  391: { label: "안전보건 순회점검 보고서", isApproval: false, usePrint: true, hideFileDownload: false, hidePrintTitle: true },
  491: { label: "안전관리자 선임보고서", isApproval: false, usePrint: true, hidePrintTitle: true, useHeaderDate: false, usePrevPost: false },
  492: { label: "비상사태훈련 결과보고서", isApproval: false, usePrint: true, hidePrintTitle: true },

  509: { label: "TBM 실행 체크리스트", isApproval: false, usePrint: true },
  510: { label: "TBM 실행 체크리스트", isApproval: false, usePrint: true },

  522: { label: "최초 위험성평가", isApproval: false, usePrint: true, printDirection: "landscape" },
  523: { label: "수시 위험성평가", isApproval: false, usePrint: true, printDirection: "landscape" },
  524: { label: "작업지휘자 지정서", isApproval: false, usePrint: true, hidePrintTitle: true,},
  525: { label: "유도원 및 신호수 지정", isApproval: false, usePrint: true },
  526: { label: "화재감시자 지정", isApproval: false, usePrint: true },
  527: { label: "안전보건 조직 체계도", isApproval: false, usePrint: true, hidePrintTitle: true },
  528: { label: "최초 TBM 회의록", detailLable:"Tool Box Meeting 회의록", isApproval: false, usePrint: true, hidePrintTitle: true },
  529: { label: "차량계 하역운반/건설기계 작업계획서", isApproval: false, usePrint: true },
  530: { label: "밀폐공간 점검 체크리스트", isApproval: false, usePrint: true },

  688: { label: "수급인 정보", isApproval: false, usePrint: true },

  846: { label: "밀폐공간 점검 체크리스트", isApproval: false, usePrint: true },
  847: { label: "화재감시자 지정", isApproval: false, usePrint: true },

  1049: { label: "최초 위험성평가(상·중·하)", isApproval: false, usePrint: true, useHeaderDate: true },
  1050: { label: "정기 위험성평가(상·중·하)", isApproval: false, usePrint: true, useHeaderDate: true },
  1051: { label: "수시 위험성평가(상·중·하)", isApproval: false, usePrint: true, useHeaderDate: true },
};
